service: whatsapppush-${self:custom.name}

frameworkVersion: '3'

plugins:
  - serverless-export-env
  - serverless-webpack

custom:
  name: giwankim
  webpack:
    includeModules: false
  package:
    individually: true
  export-env:
    overwrite: true
  TemplatesTable:
    name: !Ref TemplatesTable
    arn: !GetAtt TemplatesTable.Arn

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, 'dev'}
  region: ap-northeast-2
  versionFunctions: false
  environment:
    TEMPLATES_TABLE_NAME: ${self:custom.TemplatesTable.name}
  iam:
    role:
      statements:
        - ${file(framework/iam/TemplatesTableIAM.yml):TemplatesTableIAM}

functions:
  CreateTemplates:
    handler: handlers/template/createTemplates.handler
    description: Function to handle business logic to create templates
    events:
      - http:
          path: /templates
          method: POST
          cors: true
  UpdateTemplates:
    handler: handlers/template/updateTemplates.handler
    description: Function to handle business logic to update templates
    events:
      - http:
          path: /templates/{userId}/{templateId}
          method: PUT
          cors: true
  DeleteTemplates:
    handler: handlers/template/deleteTemplates.handler
    description: Function to handle business logic to delete templates
    events:
      - http:
          path: /templates/{userId}/{templateId}
          method: DELETE
          cors: true
  DetailsTemplates:
    handler: handlers/template/detailsTemplates.handler
    description: Function to handle business logic to get template details
    events:
      - http:
          path: /templates/{userId}/{templateId}
          method: GET
          cors: true
  ListTemplates:
    handler: handlers/template/listTemplates.handler
    description: Function to handle business logic to get all templates
    events:
      - http:
          path: /templates/{userId}
          method: GET
          cors: true

resources:
  Resources:
    TemplatesTable: ${file(framework/resources/TemplatesTable.yml):TemplatesTable}
