service: whatsapppush-${self:custom.name}

frameworkVersion: '3'

custom:
  name: giwankim
  webpack:
    includeModules: false
  package:
    individually: true
  export-env:
    overwrite: true
  logRetentionInDays: 14
  TemplatesTable:
    name: !Ref TemplatesTable
    arn: !GetAtt TemplatesTable.Arn
  RecipientFilesBucket:
    name: whatsapppush-recipient-files-gwk-${self:provider.stage}
  NotificationTaskTable:
    name: !Ref NotificationTaskTable
    arn: !GetAtt NotificationTaskTable.Arn

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, 'dev'}
  region: ap-northeast-2
  versionFunctions: false
  environment:
    TEMPLATES_TABLE_NAME: ${self:custom.TemplatesTable.name}
    RECIPIENT_FILES_BUCKET_NAME: ${self:custom.RecipientFilesBucket.name}
    NOTIFICATION_TASK_TABLE_NAME: ${self:custom.NotificationTaskTable.name}
  iam:
    role:
      statements:
        - ${file(framework/iam/TemplatesTableIAM.yml):TemplatesTableIAM}
        - ${file(framework/iam/RecipientFilesBucketIAM.yml):RecipientFilesBucketIAM}

functions:
  - ${file(framework/functions/functions-templates.yml)}
  - ${file(framework/functions/functions-upload.yml)}

resources:
  Resources:
    TemplatesTable: ${file(framework/resources/TemplatesTable.yml):TemplatesTable}
    RecipientFilesBucket: ${file(framework/resources/RecipientFilesBucket.yml):RecipientFilesBucket}
    # WhatsAppMessageQueue: ${file(framework/resources/WhatsAppMessageQueue.yml):WhatsAppMessageQueue}
    NotificationTaskTable: ${file(framework/resources/NotificationTaskTable.yml):NotificationTaskTable}

plugins:
  - serverless-export-env
  - serverless-webpack
  - serverless-plugin-log-retention
