service: whatsapppush-${self:custom.name}

frameworkVersion: '3'

custom:
  name: giwankim
  templatesTableName: Templates

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ap-northeast-2
  versionFunctions: false

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: !GetAtt TemplatesTable.Arn

functions:
  CreateTemplates:
    handler: handlers/template.create
    description: Function to handle business logic to create templates
    events:
      - http:
          path: /template
          method: POST
          cors: true
  UpdateTemplates:
    handler: handlers/template.update
    description: Function to handle business logic to update templates
    events:
      - http:
          path: /template/{user_id}/{template_id}
          method: PUT
          cors: true

resources:
  Resources:
    TemplatesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.templatesTableName}
        AttributeDefinitions:
          - AttributeName: user_id
            AttributeType: S
          - AttributeName: template_id
            AttributeType: S
        KeySchema:
          - AttributeName: user_id
            KeyType: HASH
          - AttributeName: template_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
