service: whatsapppush-${self:custom.name}

frameworkVersion: '3'

custom:
  name: giwankim
  templatesTableName: Templates

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ap-northeast-2
  versionFunctions: false

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: !GetAtt TemplatesTable.Arn

resources:
  Resources:
    TemplatesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.templatesTableName}
        AttributeDefinitions:
          - AttributeName: user_id
            AttributeType: S
          - AttributeName: template_id
            AttributeType: S
        KeySchema:
          - AttributeName: user_id
            KeyType: HASH
          - AttributeName: template_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
