service: whatsapppush-${self:custom.name}

frameworkVersion: '3'

plugins:
  - serverless-export-env

custom:
  name: giwankim
  export-env:
    overwrite: true
  TemplatesTable:
    name: !Ref TemplatesTable
    arn: !GetAtt TemplatesTable.Arn

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, 'dev'}
  region: ap-northeast-2
  versionFunctions: false
  environment:
    TEMPLATES_TABLE_NAME: ${self:custom.TemplatesTable.name}
  iam:
    role:
      statements:
        - ${file(framework/iam/TemplatesTableIAM.yml):TemplatesTableIAM}

functions:
  CreateTemplates:
    handler: handlers/template/createTemplate.handler
    description: Function to handle business logic to create templates
    events:
      - http:
          path: /templates
          method: POST
          cors: true

resources:
  Resources:
    TemplatesTable: ${file(framework/resources/TemplatesTable.yml):TemplatesTable}
  Outputs:
    TemplatesTableName:
      Value: !Ref TemplatesTable
