service: whatsapppush-${self:custom.name}

frameworkVersion: '3'

custom:
  name: giwankim
  webpack:
    includeModules: false
  package:
    individually: true
  export-env:
    overwrite: true
  logRetentionInDays: 10
  TemplatesTable:
    name: !Ref TemplatesTable
    arn: !GetAtt TemplatesTable.Arn
  RecipientFilesS3Bucket:
    name: 

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, 'dev'}
  region: ap-northeast-2
  versionFunctions: false

  environment:
    TEMPLATES_TABLE_NAME: ${self:custom.TemplatesTable.name}

  iam:
    role:
      statements:
        - ${file(framework/iam/TemplatesTableIAM.yml):TemplatesTableIAM}

functions:
  - ${file(framework/functions/functions-templates.yml)}
  
resources:
  Resources:
    TemplatesTable: ${file(framework/resources/TemplatesTable.yml):TemplatesTable}

    RecipientFilesS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.RecipientFilesS3Bucket.name}

    RecipientFilesS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref RecipientFilesS3Bucket
        PolicyDocument:
          Statement:
            - Effect: Allow
              Principal: '*'
              Action: s3:GetObject
              Resource: 

plugins:
  - serverless-export-env
  - serverless-webpack
  - serverless-plugin-log-retention
