service: whatsapppush-${self:custom.name}

frameworkVersion: '3'

plugins:
  - serverless-export-env
  - serverless-webpack

custom:
  name: giwankim
  webpack:
    includeModules: false
  package:
    individually: true
  export-env:
    overwrite: true
  TemplatesTable:
    name: !Ref TemplatesTable
    arn: !GetAtt TemplatesTable.Arn

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, 'dev'}
  region: ap-northeast-2
  versionFunctions: false
  environment:
    TEMPLATES_TABLE_NAME: ${self:custom.TemplatesTable.name}
  iam:
    role:
      statements:
        - ${file(framework/iam/TemplatesTableIAM.yml):TemplatesTableIAM}

functions:
  - ${file(framework/functions/functions-templates.yml)}
  
resources:
  Resources:
    TemplatesTable: ${file(framework/resources/TemplatesTable.yml):TemplatesTable}
