service: whatsapppush-${self:custom.name}

frameworkVersion: '3'

plugins:
  - serverless-export-env
  - serverless-plugin-log-retention
  - serverless-webpack

custom:
  name: giwankim
  webpack:
    includeModules: false
  package:
    individually: true
  export-env:
    overwrite: true
  logRetentionInDays: 7
  TemplatesTable:
    name: !Ref TemplatesTable
    arn: !GetAtt TemplatesTable.Arn
  RecipientFilesBucket:
    name: whatsapppush-recipient-files-gwk-${self:provider.stage}
  WhatsAppMessageQueue:
    url: !Ref WhatsAppMessageQueue
    name: !GetAtt WhatsAppMessageQueue.QueueName
    arn: !GetAtt WhatsAppMessageQueue.Arn
  NotificationTaskTable:
    name: !Ref NotificationTaskTable
    arn: !GetAtt NotificationTaskTable.Arn

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, 'dev'}
  region: ap-northeast-2
  versionFunctions: false
  iam:
    role:
      statements:
        - ${file(sls/iam/TemplatesTableIAM.yml):TemplatesTableIAM}
        - ${file(sls/iam/RecipientFilesBucketIAM.yml):RecipientFilesBucketIAM}
        - ${file(sls/iam/WhatsAppMessageQueueIAM.yml):WhatsAppMessageQueueIAM}
        - ${file(sls/iam/NotificationTaskTableIAM.yml):NotificationTaskTableIAM}

  environment:
    REGION: ${self:provider.region}
    TEMPLATES_TABLE_NAME: ${self:custom.TemplatesTable.name}
    RECIPIENT_FILES_BUCKET_NAME: ${self:custom.RecipientFilesBucket.name}
    WHATSAPP_MESSAGE_QUEUE_URL: ${self:custom.WhatsAppMessageQueue.url}
    NOTIFICATION_TASK_TABLE_NAME: ${self:custom.NotificationTaskTable.name}

functions:
  - ${file(sls/functions/functions-templates.yml)}
  - ${file(sls/functions/functions-upload.yml)}
  - ${file(sls/functions/functions-notification.yml)}

resources:
  Resources:
    TemplatesTable: ${file(sls/resources/TemplatesTable.yml):TemplatesTable}
    RecipientFilesBucket: ${file(sls/resources/RecipientFilesBucket.yml):RecipientFilesBucket}
    WhatsAppMessageQueue: ${file(sls/resources/WhatsAppMessageQueue.yml):WhatsAppMessageQueue}
    NotificationTaskTable: ${file(sls/resources/NotificationTaskTable.yml):NotificationTaskTable}
