NotificationTaskTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: NotificationTaskTable-${self:provider.stage}
    AttributeDefinitions:
      - AttributeName: user_id
        AttributeType: S
      - AttributeName: notification_id
        AttributeType: S
    KeySchema:
      - AttributeName: user_id
        KeyType: HASH
      - AttributeName: notification_id
        KeyType: RANGE
    BillingMode: PAY_PER_REQUEST
