TemplatesTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: TemplatesTable-${self:provider.stage}
    AttributeDefinitions:
      - AttributeName: user_id
        AttributeType: S
      - AttributeName: template_id
        AttributeType: S
    KeySchema:
      - AttributeName: user_id
        KeyType: HASH
      - AttributeName: template_id
        KeyType: RANGE
    BillingMode: PAY_PER_REQUEST
